version: "3.9"
services:
  client:
    build: client/.
    network_mode: 'host'
    restart: 'always'
  server:
    build: server/.
    network_mode: 'host'
    restart: 'always'
    env_file:
    - .env
  # nginx:
  #   build: next-client/nginx/.
  #   network_mode: 'host'
  #   restart: 'always'
  #   depends_on:
  #   - next-client
  next-client:
    build: next-client/.
    network_mode: 'host'
    restart: 'always'
    depends_on:
      - server