version: "3.9"
services:
  client:
    build: client/.
    network_mode: 'host'
    restart: 'always'
  server:
    build: server/.
    network_mode: 'host'
    restart: 'always'
    env_file:
    - .env